name: 'Kubernetes DigitalOcean Cluster'
description: 'Manage DigitalOcean Kubernetes cluster lifecycle'

inputs:
  # TODO required for private repositories only
  # How to create a PAT
  # https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/creating-a-personal-access-token
  github-token:
    description: 'GitHub token required to download the cluster configurations when the repository is private'
    required: true
  access-token:
    description: 'Digital Ocean access token required to provision clusters'
    required: true
  config-path:
    description: 'Path to the cluster configuration file'
    required: true
  config-branch:
    description: 'Branch of the cluster configuration file'
    required: false
  enabled:
    description: 'Dry run if set to false'
    required: false
    default: true
  wait:
    description: 'Wait for the cluster to be provisioned before exit'
    required: false
    default: false
  skip-create:
    description: 'Ignore provisioning. If cluster status is UP download kubeconfig only: useful for development'
    required: false
    default: false
outputs:
  status:
    description: 'Current status of the cluster: [DISABLE|CREATE|DELETE|UP|DOWN|ERROR]'
  kubeconfig:
    description: 'Path to kubeconfig file e.g. ./OWNER-REPOSITORY-kubeconfig.yaml'

runs:
  using: docker
  image: Dockerfile
  args:
    - ${{ inputs.github-token }}
    - ${{ inputs.access-token }}
    - ${{ inputs.config-path }}
    - ${{ inputs.config-branch }}
    - ${{ inputs.enabled }}
    - ${{ inputs.wait }}
    - ${{ inputs.skip-create }}
