{{ if eq .Values.operator "external-secrets-akeyless" }}
---
apiVersion: v1
kind: Secret
metadata:
  name: external-secrets-akeyless-credentials
  labels: 
    type: akeyless
type: Opaque
stringData:
  accessId: {{ .Values.externalSecrets.akeyless.accessId }}
  accessType: {{ .Values.externalSecrets.akeyless.accessType }}
  accessTypeParam: {{ .Values.externalSecrets.akeyless.accessTypeParam }}
{{ end }}
