{{ if eq .Values.provider "oracle" }}
---
apiVersion: v1
kind: Secret
metadata:
  name: oracle-secret
  labels: 
    type: oracle
type: Opaque
stringData:
  privateKey: {{ .Values.oracle.privateKey }}
  fingerprint: {{ .Values.oracle.fingerprint }}
{{ end }}
