name: docker-ci

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/docker-*.yml'
      - 'docker/**'
    # uses semver with prefix to keep image tags independent from action tags
    tags:
      - 'docker-[0-9]+.[0-9]+.[0-9]+'

env:
  DOCKER_REPOSITORY: hckops

jobs:
  docker:
    name: Docker
    runs-on: ubuntu-22.04
    # makes sure it doesn't finish the minutes quota if stalls
    timeout-minutes: 15
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      # extracts tag from ref, returns semver tag or sha suffix
      - name: Get Docker tag
        id: get-docker-tag
        env:
          GITHUB_REF: ${{ github.ref }}
          COMMIT_SHA: ${{ github.sha }}
        run: |
          if [[ ${{ github.ref_type }} == "tag" ]]; then
            echo "tag=${GITHUB_REF#refs/tags/docker-}" >> ${GITHUB_OUTPUT}
          else
            echo "tag=${COMMIT_SHA:0:7}" >> ${GITHUB_OUTPUT}
          fi
      
      - name: Output Docker tag
        run: echo ${{ steps.get-docker-tag.outputs.tag }}
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # gh-actions-rw
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push [${{ env.DOCKER_IMAGE_NAME }}]
        uses: docker/build-push-action@v4
        env:
          DOCKER_IMAGE_NAME: kube-base
        with:
          context: ./docker
          file: ./docker/Dockerfile.base
          # if false it will only build
          push: true
          tags: |
            ${{ env.DOCKER_REPOSITORY }}/${{ env.DOCKER_IMAGE_NAME }}:latest
            ${{ env.DOCKER_REPOSITORY }}/${{ env.DOCKER_IMAGE_NAME }}:${{ steps.get-docker-tag.outputs.tag }}
      
      - name: Build and push [${{ env.DOCKER_IMAGE_NAME }}]
        uses: docker/build-push-action@v4
        env:
          DOCKER_IMAGE_NAME: kube-argo
        with:
          context: ./docker
          file: ./docker/Dockerfile.argo
          push: true
          tags: |
            ${{ env.DOCKER_REPOSITORY }}/${{ env.DOCKER_IMAGE_NAME }}:latest
            ${{ env.DOCKER_REPOSITORY }}/${{ env.DOCKER_IMAGE_NAME }}:${{ steps.get-docker-tag.outputs.tag }}

      - name: Build and push [${{ env.DOCKER_IMAGE_NAME }}]
        uses: docker/build-push-action@v4
        env:
          DOCKER_IMAGE_NAME: kube-do
        with:
          context: ./docker
          file: ./docker/Dockerfile.do
          push: true
          tags: |
            ${{ env.DOCKER_REPOSITORY }}/${{ env.DOCKER_IMAGE_NAME }}:latest
            ${{ env.DOCKER_REPOSITORY }}/${{ env.DOCKER_IMAGE_NAME }}:${{ steps.get-docker-tag.outputs.tag }}

      - name: Build and push [${{ env.DOCKER_IMAGE_NAME }}]
        uses: docker/build-push-action@v4
        env:
          DOCKER_IMAGE_NAME: kube-aws
        with:
          context: ./docker
          file: ./docker/Dockerfile.aws
          push: true
          tags: |
            ${{ env.DOCKER_REPOSITORY }}/${{ env.DOCKER_IMAGE_NAME }}:latest
            ${{ env.DOCKER_REPOSITORY }}/${{ env.DOCKER_IMAGE_NAME }}:${{ steps.get-docker-tag.outputs.tag }}
