name: test-kube

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/test-kube.yml'
      - 'examples/kube-*.yaml'
      - 'kube-do-action/**'

jobs:
  test-kube-do:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Provision
        uses: ./kube-do-action
        id: provision
        with:
          github-token: ${{ github.token }}
          access-token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
          config-path: examples/kube-do-sample.yaml
          # action is disabled
          enabled: false
      - name: Status
        run: echo "Cluster status ${{ steps.provision.outputs.status }}"
