name: Test Kubernetes DigitalOcean

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/test-kube-*.yml'
      - 'examples/kube-*.yaml'
      - 'kube-do-action/**'

# TODO notification
jobs:
  test-kube-do:
    name: Test
    runs-on: ubuntu-latest
    steps:
      # TODO private repository only
      - name: Checkout
        uses: actions/checkout@v3

      # TODO add tmp shared path to save kubeconfig (bootstrap)
      - name: Test input
        uses: ./kube-do-action
        id: test-input
        with:
          github-token: ${{ github.token }}
          access-token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
          config-path: examples/kube-do-sample.yaml
          enabled: true

      - name: Test output
        run: echo "Output status ${{ steps.test-input.outputs.status }}"
