name: test-kube-secrets

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/test-kube-secrets.yml'
      - 'kube-secrets-action/**'

jobs:
  test-kube-secrets:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: "Invalid kubeconfig"
        run: |
          echo "test: 1" > config.yaml

      - name: Secrets
        uses: ./kube-secrets-action
        with:
          kubeconfig: ./config.yaml
          edgelevel-lastpass-username: TEST_LASTPASS_USERNAME
          edgelevel-lastpass-password: TEST_LASTPASS_PASSWORD
          external-secrets-oracle-private-key: TEST_ORACLE_PRIVATE_KEY
          external-secrets-oracle-fingerprint: TEST_ORACLE_FINGERPRINT
