name: test-ci

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/test-ci.yml'
      - 'helm-lint-action/**'

jobs:
  ci:
    name: Continuos Integration
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Helm Lint
        uses: ./helm-lint-action
