name: test-kube-do

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/test-kube-do.yml'
      - 'kube-do-action/**'
      - 'examples/kube-*.yaml'

jobs:
  test-kube-do:
    name: Test
    runs-on: ubuntu-latest
    steps:
      # required to access cluster definition
      - name: Checkout
        uses: actions/checkout@v3

      - name: Provision
        uses: ./kube-do-action
        id: provision
        with:
          github-token: ${{ github.token }}
          access-token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
          config-path: examples/kube-test-do-lon1.yaml
          # action is disabled
          enabled: false
          wait: false

      - name: Output
        run: |
          echo "Status ${{ steps.provision.outputs.status }}"
          echo "Config ${{ steps.provision.outputs.config }}"
