name: 'Helm Dependencies'
description: 'Keep Helm dependencies updated'

inputs:
  github-token:
    description: 'GitHub token required to open pull requests'
    required: true
  user-email:
    description: 'user.email to configure git'
    required: true
  user-name:
    description: 'user.name to configure git'
    required: true
  default-branch:
    description: 'Repository default branch'
    required: false
    default: ${{ github.event.repository.default_branch }}
  config-path:
    description: 'Path to the dependencies configuration file'
    required: true
  dry-run:
    description: 'Skip pull requests if set to true'
    required: false
    default: false

runs:
  using: docker
  image: Dockerfile
  args:
    - ${{ inputs.github-token }}
    - ${{ inputs.user-email }}
    - ${{ inputs.user-name }}
    - ${{ inputs.default-branch }}
    - ${{ inputs.config-path }}
    - ${{ inputs.dry-run }}
