name: 'Helm Dependencies'
description: 'Keep Helm dependencies updated'

inputs:
  config-path:
    description: 'Path to the dependencies configuration file'
    required: true
  user-email:
    description: 'user.email to configure git'
    required: true
  user-name:
    description: 'user.name to configure git'
    required: true
  dry-run:
    description: 'Skip pull requests if set to true'
    required: false
    default: false

runs:
  using: docker
  image: Dockerfile
  args:
    - ${{ inputs.config-path }}
    - ${{ inputs.user-email }}
    - ${{ inputs.user-name }}
    - ${{ inputs.dry-run }}
